# Generated by Django 4.0.5 on 2022-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('number', models.IntegerField()),
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('price_usd', models.IntegerField()),
                ('price_rub', models.FloatField()),
                ('delivery', models.CharField(max_length=200)),
            ],
        ),
    ]
