# Generated by Django 4.0.5 on 2022-06-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['number']},
        ),
    ]
